from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a32f6005736'
down_revision = '18c007d396e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        # Allow the 'password_hash' column to be nullable initially to avoid issues with existing data
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # Set a default password hash for existing records
    op.execute("UPDATE student SET password_hash = '' WHERE password_hash IS NULL")

    # After updating existing records, alter the column to be NOT NULL
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('password_hash', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
