"""Add user_id to Job model

Revision ID: cb56f3ab97a0
Revises: 7a32f6005736
Create Date: 2025-01-31 03:04:45.951784
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb56f3ab97a0'
down_revision = '7a32f6005736'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Add constraint with a name
        batch_op.create_foreign_key('fk_job_user', 'student', ['user_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        # Drop constraint with the name
        batch_op.drop_constraint('fk_job_user', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
